// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: echo.proto

package cz.scholz.grpcecho.proto;

public interface EchoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:echo.EchoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
